# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "natapat-terraform-state"
    credentials = "/Users/darvel/git/labs/darnattp/terraform-gcp/terraform-credentials.json"
    prefix      = "dev/network/terraform.tfstate"
  }
}
