# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  credentials = "../../../../../../terraform-credentials.json"
  project = "devops-00000"
  region  = "asia-southeast1"
}
provider "google-beta" {
  credentials = "../../../../../../terraform-credentials.json"
  project = "devops-00000"
  region  = "asia-southeast1"
}
